### PR TITLE
fixed some issues and added `for` loop in logic

### PR DESCRIPTION
**Pull request by 0xrisec**
1.Take advantage of a for loop and file read: most of the payloads have the same code, so we can use a for loop except for repeated code. for the URL_Encode_Bypass and SQLi_libinjection payloads, I have created separate files.

2.In each payload, the -L flag is added to all curl commands to redirect 302.

3.Removed duplicates payloads : 
dublicate-entries-httpHeaders

4.The path and domain commands generate incorrect output: this one is also fixed
pathdomain

5. Most of the time, the server does not respond to the HEAD verb, so the HEAD verb was removed from HTTP method payloads. ex: `bash 403-bypass.sh -u www.google.com --HTTPmethod`

### CODE REVIEW

**Comment by Dheerajmadhukar** [comment]
Thanks for your efforts my friend. But there is a reason i am not using `for` loop. 
But i appreciate your work. I will remove those duplicate payload entries. :)

Feel free to comment your thoughts.

**Comment by 0xrisec** [comment]
what about 4th point `The path and domain commands generate incorrect output` ?
domain

**Comment by 0xrisec** [comment]
correction of domain command(above image in my terminal) , I have put extra `-` in last so i have removed it, so now its same as your code
correction

**Comment by Dheerajmadhukar** [comment]
The implementation was correct in 4-ZERO-3. Please check the README.md again, you will see that you need to pass the target as `scheme://domain/path` like `https://domain/path`.

If you are satisfied with the same, kindly close it.

Thanks for your efforts :)

**Pull request closed without merging**
